### ISSUE TITLE
Invalid Action

### ISSUE THREAD

**Issue by rudycox** [mavericksthinker/cordova-plugin-printerplugin#2]
Hi I'm trying to use your plugin.
I've installed into my app and just to test I made:
function onDeviceReady(){
	CordovaPrint.wifiList(function(data){
        console.log("Success");
        console.log(data); //list of printer in data array
    },function(err){
        console.log("Error");
        console.log(err);
    })
} 

but in console I get
Error
Invalid Action

May be I'm doing wrong or missing something.
Could you help me?

**Comment by ericomballus** [comment]
same to me...please help me!

**Comment by mavericksthinker** [comment]
@rudycox @ericomballus I have created this sample app for reference you can have a look and follow along https://github.com/mavericksthinker/TestAppForPrinting

**Comment by rudycox** [comment]
thank you.
I downloaded, built and run the app, but there is something wrong.

Any button I press I get  'CordovaPrint is not defined     at wrapper.js line##'   

Any suggestion?

**Comment by rudycox** [comment]
![Immagine](https://user-images.githubusercontent.com/40353924/93606108-e8564f00-f9c7-11ea-94cb-37a560b8ace1.png)

**Comment by rudycox** [comment]
I also commented all lines from #56 to  #145
now no errors but same result 'invalid action'

**Comment by mavericksthinker** [comment]
@rudycox
 `CordovaPrint is not defined` signifies the printer-plugin is not configured properly. I have update package.json, you can give it a try. Currently I dont have my dev env setup for this but if you still facing issue, I will try to make a new working project and update it.

**Comment by rudycox** [comment]
ok, deleted everything
cloned
built 
run
same error: CordovaPint is not defined wrapper.js
and same result

index.js:59 Invalid action
index.js:68 Unable to initiate
index.js:69 Invalid action
index.js:78 Error
index.js:79 Invalid action
index.js:84 Unable to dismiss
index.js:85 Invalid action

what is missing?

I forgot that now and before I had to modify androidmanifest.xml (the reference to the icon is invalid and build stops with error)
From:
 <application android:hardwareAccelerated="true" android:icon="@mipmap/print" android:label="@string/app_name" android:supportsRtl="true">
To:
(I forgot to say that there is an invalid setting in andoidmanifest.xml
 <application android:hardwareAccelerated="true"  android:label="@string/app_name" android:supportsRtl="true">

**Comment by rudycox** [comment]
FROM: 
` <application android:hardwareAccelerated="true" android:icon="@mipmap/print" android:label="@string/app_name" android:supportsRtl="true">`
TO:
` <application android:hardwareAccelerated="true" android:label="@string/app_name" android:supportsRtl="true">`

**Comment by Bubelbub** [comment]
Hi @rudycox @mavericksthinker @ericomballus:

Yes you're right.
This is an issue with the JS implementation here.

https://github.com/mavericksthinker/cordova-plugin-printerplugin/blob/master/www/PrintingPlugin.js#L7

There are no `bluetoothPrinterList`, `wifiPrinterList` and `usbPrinterList` commands.
You can simply test a workflow with this few lines of code.

### Get your devices

    Cordova.exec(a => console.log('OK', a), e => console.warn('ERR', e), 'PrintingPlugin', 'list', []);

This return something like:

    ["POS58 Printer USB       "]

### Connect to your device

    Cordova.exec(a => console.log('OK', a), e => console.warn('ERR', e), 'PrintingPlugin', 'connect', ['POS58 Printer USB       '])

### Prepare text for printing

    Cordova.exec(a => console.log('OK', a), e => console.warn('ERR', e), 'PrintingPlugin', 'printText', ['Hello World\n'])

### Print it

This command works because the action equals the `PrintingPlugin.js`.

    CordovaPrint.print(function(data) {
        console.log("Success"); console.log(data);
    }, function(err) {
        console.log("Error"); console.log(err);
    })



I got it working with that. 🥳

**Comment by mavericksthinker** [comment]
Thanks @Bubelbub for the PR.
